meta:
  version: 2
  flow: FABulousTile

FABULOUS_TILE_DIR: dir::.

# Basics
DESIGN_NAME: SW_GF_term
VERILOG_FILES:
  - dir::../../../models_pack.v
  - dir::../../../custom.v

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: N_GBUF_END[0]
FABULOUS_EXTERNAL_SIDE: S
