meta:
  version: 2
  flow: FABulousTile

FABULOUS_TILE_DIR: dir::.

# Basics
DESIGN_NAME: E_GF_SRAM_single
VERILOG_FILES:
  - dir::../../../models_pack.v
  - dir::../../../custom.v
FABULOUS_EXTERNAL_SIDE: E

# Disable timing driven placement
# as it would resize the buffers
PL_TIME_DRIVEN: false

# Seems to add a few buffers too
PL_ROUTABILITY_DRIVEN: false

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: N_GBUF_END[0]
