name: CI

# Events that trigger the workflow
on:
  # Runs on all pushes to branches
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  # Runs on all PRs
  pull_request:
  # Manual Dispatch
  workflow_dispatch:

concurrency:
  # Behavior:
  # - Group all pull requests: latest push cancels previous ones
  # - Group all branches:
  #   - If main/version- branches: run serially
  #   - Else, latest push cancels previous ones
  group: >
    ${{
      (github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number)) ||
      (github.event_name == 'push' && format('branch-{0}', github.ref_name)) ||
      ''
    }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || !(startsWith(github.ref_name, 'version-') || github.ref_name == 'main' || github.ref_name == 'dev') }}

jobs:
  tiles:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        pdk: [gf180mcuD]
        tile_library: [classic]
        scl: [gf180mcu_as_sc_mcu7t3v3]
    name: Tiles (${{ matrix.tile_library }}/${{ matrix.pdk }}/${{ matrix.scl }})
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Setup Nix
        uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the tile library hash
        run: |
          echo "TILE_LIBRARY_SHORT_HASH=$(git rev-parse --short HEAD:ip/fabulous-tiles)" >> $GITHUB_ENV
      - name: Cache the tiles
        uses: actions/cache@v5
        id: cache
        with:
          path: ip/fabulous-tiles/tiles
          key: cache-tiles-${{ matrix.tile_library }}-${{ matrix.pdk }}-${{ matrix.scl }}-${{ env.TILE_LIBRARY_SHORT_HASH }}
      - name: Implement the tiles
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          make tiles

  extra-tiles:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        pdk: [gf180mcuD]
        tile_library: [classic]
        scl: [gf180mcu_as_sc_mcu7t3v3]
    name: Extra Tiles (${{ matrix.tile_library }}/${{ matrix.pdk }}/${{ matrix.scl }})
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Setup Nix
        uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the tile library hash
        run: |
          echo "EXTRA_TILE_LIBRARY_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Cache the tiles
        uses: actions/cache@v5
        id: cache
        with:
          path: ip/extra-tiles/tiles
          key: cache-extra-tiles-${{ matrix.tile_library }}-${{ matrix.pdk }}-${{ matrix.scl }}-${{ env.EXTRA_TILE_LIBRARY_SHORT_HASH }}
      - name: Implement the tiles
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          make extra-tiles

  fabrics:
    runs-on: ubuntu-24.04
    needs: [tiles, extra-tiles]
    strategy:
      matrix:
        pdk: [gf180mcuD]
        fabric: [classic_fabric_wsrun2]
        scl: [gf180mcu_as_sc_mcu7t3v3]
    name: Fabric (${{ matrix.fabric }}/${{ matrix.pdk }}/${{ matrix.scl }})
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Setup Nix
        uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the tile library
        run: |
          echo "TILE_LIBRARY=$(echo "${{ matrix.fabric }}" | cut -d'_' -f1)" >> $GITHUB_ENV
          echo "TILE_LIBRARY_SHORT_HASH=$(git rev-parse --short HEAD:ip/fabulous-tiles)" >> $GITHUB_ENV
          echo "REPO_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Restore Tiles
        uses: actions/cache/restore@v5
        with:
          path: ip/fabulous-tiles/tiles
          key: cache-tiles-${{ env.TILE_LIBRARY }}-${{ matrix.pdk }}-${{ matrix.scl }}-${{ env.TILE_LIBRARY_SHORT_HASH }}
          fail-on-cache-miss: true
      - name: Restore Extra Tiles
        uses: actions/cache/restore@v5
        with:
          path: ip/extra-tiles/tiles
          key: cache-extra-tiles-${{ env.TILE_LIBRARY }}-${{ matrix.pdk }}-${{ matrix.scl }}-${{ env.REPO_SHORT_HASH }}
          fail-on-cache-miss: true
      - name: Cache the Fabric
        uses: actions/cache@v5
        with:
          path: ip/fabulous-fabrics/fabrics/${{ matrix.fabric }}/macro/${{ matrix.pdk }}/
          key: cache-fabric-${{ matrix.fabric }}-${{ matrix.pdk }}-${{ matrix.scl }}-${{ env.REPO_SHORT_HASH }}
      - name: Stitch the Fabric
        run: |
          make fabric
      - name: Upload Macro Folder
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.fabric }}_${{ matrix.pdk }}_${{ matrix.scl }}
          path: ip/fabulous-fabrics/fabrics/${{ matrix.fabric }}/macro/${{ matrix.pdk }}/
          include-hidden-files: true
      - name: Cache the User Designs
        uses: actions/cache@v5
        with:
          path: ip/fabulous-fabrics/user_designs/
          key: cache-user-designs-${{ matrix.fabric }}-${{ matrix.pdk }}-${{ matrix.scl }}-${{ env.REPO_SHORT_HASH }}
      - name: Implement the User Designs
        run: |
          cd ip/fabulous-fabrics/user_designs; PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabric }} nix develop --command make all
      - name: Simulate the Fabric (RTL Emulation)
        run: |
          cd ip/fabulous-fabrics; EMULATION=counter PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabric }} nix develop --command bash -c "cd tb; python3 fabric_tb.py"
      - name: Simulate the Fabric (RTL Simulation)
        run: |
          cd ip/fabulous-fabrics; PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabric }} nix develop --command bash -c "cd tb; python3 fabric_tb.py"

  chip:
    runs-on: ubuntu-24.04
    name: Build the Chip
    needs:
      - fabrics
    strategy:
      matrix:
        pdk: [gf180mcuD]
        fabric: [classic_fabric_wsrun2]
        scl: [gf180mcu_as_sc_mcu7t3v3]
        slot: [default]
        sram: [default]
        pad: [default]
        domain: [default]
    steps:
      - name: Set variables
        run: |
          echo "SLOT=${{ matrix.slot }}" >> $GITHUB_ENV
          echo "SRAM=${{ matrix.sram }}" >> $GITHUB_ENV
          echo "PAD=${{ matrix.pad }}" >> $GITHUB_ENV
          echo "SCL=${{ matrix.scl }}" >> $GITHUB_ENV
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Setup Nix
        uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: x86_64-linux
      - name: Check Nix
        run: |
          sudo du -hs /nix/store/* | sort -h | tail -n 10
          sudo tree /nix/store/*-librelane || true
      - name: Get the tile library
        run: |
          echo "TILE_LIBRARY=$(echo "${{ matrix.fabric }}" | cut -d'_' -f1)" >> $GITHUB_ENV
          echo "TILE_LIBRARY_SHORT_HASH=$(git rev-parse --short HEAD:ip/fabulous-tiles)" >> $GITHUB_ENV
          echo "REPO_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Restore Tiles
        uses: actions/cache/restore@v5
        with:
          path: ip/fabulous-tiles/tiles
          key: cache-tiles-${{ env.TILE_LIBRARY }}-${{ matrix.pdk }}-${{ matrix.scl }}-${{ env.TILE_LIBRARY_SHORT_HASH }}
          fail-on-cache-miss: true
      - name: Restore Extra Tiles
        uses: actions/cache/restore@v5
        with:
          path: ip/extra-tiles/tiles
          key: cache-extra-tiles-${{ env.TILE_LIBRARY }}-${{ matrix.pdk }}-${{ matrix.scl }}-${{ env.REPO_SHORT_HASH }}
          fail-on-cache-miss: true
      - name: Restore Fabric
        uses: actions/cache/restore@v5
        with:
          path: ip/fabulous-fabrics/fabrics/${{ matrix.fabric }}/macro/${{ matrix.pdk }}/
          key: cache-fabric-${{ matrix.fabric }}-${{ matrix.pdk }}-${{ matrix.scl }}-${{ env.REPO_SHORT_HASH }}
          fail-on-cache-miss: true
      - name: Restore User Designs
        uses: actions/cache/restore@v5
        with:
          path: ip/fabulous-fabrics/user_designs/
          key: cache-user-designs-${{ matrix.fabric }}-${{ matrix.pdk }}-${{ matrix.scl }}-${{ env.REPO_SHORT_HASH }}
          fail-on-cache-miss: true
      - name: Clone the PDK
        run: |
          nix develop --command make clone-pdk
      - name: Run RTL simulation (all_ones)
        run: |
          TESTCASE=all_ones nix develop --command make sim
          # cocotb also returns 0 upon failure
          # check the simulation results
          ! grep failure cocotb/sim_build/results.xml
      - name: Run RTL simulation (all_zeros)
        run: |
          TESTCASE=all_zeros nix develop --command make sim
          # cocotb also returns 0 upon failure
          # check the simulation results
          ! grep failure cocotb/sim_build/results.xml
      - name: Run RTL simulation (counter_top)
        run: |
          TESTCASE=counter_top nix develop --command make sim
          # cocotb also returns 0 upon failure
          # check the simulation results
          ! grep failure cocotb/sim_build/results.xml
      - name: Run RTL simulation (trigger_slot)
        run: |
          TESTCASE=trigger_slot nix develop --command make sim
          # cocotb also returns 0 upon failure
          # check the simulation results
          ! grep failure cocotb/sim_build/results.xml
      - name: Implement the Chip
        if: success() || failure()
        run: |
          nix develop --command make librelane-condensed
      - name: Create summary
        if: success() || failure()
        run: |
          echo "# Manufacturability" >> $GITHUB_STEP_SUMMARY
          cat librelane/runs/*/*-misc-reportmanufacturability/manufacturability.rpt >> $GITHUB_STEP_SUMMARY
      - name: Print the hash
        if: success() || failure()
        run: |
          shasum final/gds/*
      - name: Upload GDS
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.slot }}_${{ matrix.domain }}_gds
          path: final/gds/*
      - name: Upload image
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.slot }}_${{ matrix.domain }}_image
          path: final/render/*.png
      #- name: Run GL simulation
      #  if: success() || failure()
      #  run: |
      #    nix develop --command make sim-gl
      #    # cocotb also returns 0 upon failure
      #    # check the simulation results
      #    ! grep failure cocotb/sim_build/results.xml
